# Generated by Django 2.1.4 on 2018-12-10 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my', '0002_auto_20181210_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(blank=True, max_length=128, null=True, verbose_name='姓名')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='详细地址')),
                ('is_default', models.BooleanField(verbose_name='默认地址')),
                ('province', models.CharField(blank=True, max_length=128, null=True, verbose_name='省')),
                ('city', models.CharField(blank=True, max_length=128, null=True, verbose_name='市')),
                ('county', models.CharField(blank=True, max_length=128, null=True, verbose_name='区/县')),
                ('telephone', models.CharField(blank=True, max_length=50, verbose_name='电话')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
