# Generated by Django 2.1.4 on 2018-12-10 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0003_useraddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='realname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='telephone',
            new_name='tel',
        ),
    ]
