# Generated by Django 2.1.4 on 2018-12-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0004_auto_20181210_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='area_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='areaCode'),
        ),
    ]
