# Generated by Django 2.1.4 on 2018-12-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20181206_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='pic_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
