# Generated by Django 2.1.4 on 2018-12-14 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_good_pic_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='blob',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='props', to='goods.Good'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
