# Generated by Django 2.1.4 on 2018-12-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20181210_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='tel',
            field=models.CharField(blank=True, max_length=50, verbose_name='电话'),
        ),
    ]
